services:
  - type: web
    name: fake-news-detector
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m nltk.downloader stopwords
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
